### ISSUE TITLE
[Bug] Soul Elytra Boost does not work in Trinket Cape slot

### ISSUE THREAD

**Issue by twenty41** [KyaniteMods/DeeperAndDarker#371] opened 2024-09-11 02:50 UTC
**Minecraft Version**: 1.21
**Mod Version**: 9.0.0
**Mod Loader**: fabric 0.16.5

**Description**:
I use Trinkets and Elytra Slot, as I think tons and tons of people also do. So Elytras can be used in the cape slot, alongside chestplates.

The Soul Elytra works in this slot, but only as a normal Elytra. The boost hotkey does not work, and fills in with "Left Shift" though that also does nothing.

**To Reproduce**:
With Trinkets and Elytra slot, try boosting with the Soul Elytra

**Screenshots**:
In the chestplate slot:

![2024-09-10_22 22 32](https://github.com/user-attachments/assets/b6eb93a7-4ad8-462c-98c4-4fd5748cb5d4)

In the Cape slot, via Elytra Slot mod:

![2024-09-10_22 22 25](https://github.com/user-attachments/assets/98b4e08b-68d7-4505-861c-65f54421feb8)

**Additional context**:
If there is any way I could bridge this compatibility myself let me know. But I think this is a very common combination of mods that may be worth official compat

**Comment by NolanHewitt** [comment] 2024-09-12 14:14
This would probably have to be fixed by the elytra slot mod. It works in the previous version of Deeper and Darker (1.2.6). Also duplicate of #335

**Comment by Fyoncle** [comment] 2024-10-11 01:11
Even tho ElytraSlot fixed their problem, that issue still remains because keybinds like Shift, CTRL, ALT and other ones does NOT work. Only normal keybinds like A B C D

**Closed as completed** 2024-12-09 13:29 UTC
Labels: bug
