### ISSUE TITLE
Crash in ATM 8 Modpack

### ISSUE THREAD

**Issue by Charismara** [KyaniteMods/DeeperAndDarker#128] opened 2023-01-15 08:27 UTC
**Mod Version**: 1.1.6

**Mod Loader**: forge
**Description**:
Client & Server crashes. The Server can not be started again since it always crashes

**Additional context**:
Client Crash Report:
[crash-2023-01-15_09.24.49-client.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/10419740/crash-2023-01-15_09.24.49-client.txt)

Server Crash Report:
[crash-2023-01-15_08.24.51-server.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/10419743/crash-2023-01-15_08.24.51-server.txt)

**Comment by Kisonu** [comment] 2023-02-06 05:21
Already made a comment in the modpack git, but was curious if there was a way to prevent this issue from occurring or prevent the mob from spawning? Figured I'd ask in both just in case...

**Comment by garyoneillj** [comment] 2023-07-20 09:56
Is there any fix for this? Currently experiencing the same issue in my ATM8 server, crashes as soon as we try to load in.

**Comment by garyoneillj** [comment] 2023-07-20 10:09
> Is there any fix for this? Currently experiencing the same issue in my ATM8 server, crashes as soon as we try to load in.

Issue was caused by one player loading in, by the sculk mobs (unsure which).  Another player managed to load in (spawned in different area) and killed all the sculk mobs, which fixed the issue for us.

**Comment by Micaxs** [comment] 2023-07-22 19:06
Just yeet this mod from your pack / server. Or disable the spawning inside the config file if it allows you to without having config mismatch errors.

**Closed** 2023-10-18 20:44 UTC
Labels: bug, forge
