### ISSUE TITLE
Sculk Transmitter allows for easy item duplication

### ISSUE THREAD

**Issue by iTriedGit** [KyaniteMods/DeeperAndDarker#325] opened 2024-07-31 23:10 UTC
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.1
**Mod Loader**:  Forge

**Description**:
Sculk Transmitter allows for easy item duplication. Items don't get removed from the chest,

**To Reproduce**:
1. Use the sculk transmitter to open an unloaded chest
2. Take anything out
3. Close it
4. Open it again to reveal that items are still there

**Comment by NewJumper** [comment] 2024-08-03 19:32
duplicate of #292

**Closed as not planned by NewJumper** 2024-08-03 19:32 UTC
Labels: bug, duplicate
