### ISSUE TITLE
My minecraft server crash with these mods i don't know what to do

### ISSUE THREAD

**Issue by LeYakuzaFou** [KyaniteMods/DeeperAndDarker#174] opened 2023-06-19 15:47 UTC
**Mod Version**: 1.19.2

**Mod Loader**: forge

**Description**:
My server crash when i launch it

**To Reproduce**:
Launch the server

**Screenshots**:
![Capture d'écran 2023-06-19 174610](https://github.com/KyaniteMods/DeeperAndDarker/assets/90041181/7ac97402-d6fe-4005-b3e2-0abba6104c13)

**Additional context**:
![Capture d'écran 2023-06-19 172908](https://github.com/KyaniteMods/DeeperAndDarker/assets/90041181/f05e0e98-e1d0-4134-ac25-c5af53a556a1)

**Comment by NewJumper** [comment] 2023-07-21 05:28
could you try reproducing this crash with only deeper darker? if not, it is most likely another mod.

**Comment by vgrynch** [comment] 2023-07-23 05:52
Adding here - getting the same issue on my server. 
This is NOT the other mods issue. This is the way how snakeyaml lib is packaged. From what I have read, this is most likely related to the use of much newer version of the library comparing to what the majority of mods are using for version 1.19.2. Or it is related to the way of packaging (possibly, try to exclude the lib, it is already included in the Forge).

**Comment by vgrynch** [comment] 2023-07-23 05:56
So, to understand the problem: there is a lib version loading collision in here. I'm getting this error for different library or mod every time I start the server. Sometimes I get it like this:
```
java.lang.module.ResolutionException: Module org.lz4.pure.java reads more than one module named org.yaml.snakeyaml
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:722)
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(Mod
```

And sometimes like this:
```
java.lang.module.ResolutionException: Module forge reads more than one module named org.yaml.snakeyaml
at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:722)
at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
```

I have tried different versions of DeeperAndDarker mod for 1.19.2, and version 1.1.3 of the MOD worked for me. 1.1.6 did not.

Please, fix.

**Comment by NewJumper** [comment] 2023-07-24 04:43
hmm i've never seen this error before

**Comment by NewJumper** [comment] 2023-07-24 04:45
i am also unable to reproduce it, but maybe this issue has been fixed in dev. i'd say wait until the next update of deeper darker to see if the error still persists

**Closed as completed** 2023-10-22 23:02 UTC
Labels: bug, forge, needs testing
