### ISSUE TITLE
Armor Trims

### ISSUE THREAD

**Issue by 10restart** [KyaniteMods/DeeperAndDarker#330] opened 2024-08-11 13:18 UTC
**Description**:
What feature do you think would make Deeper and Darker better? Provide examples of how to obtain it and its uses.
Hello, I've must say that Deeper and Darker mod is a mod which ive been using for a long time now and i haven't experienced any mods since then, but i've must say that theres one special thing that i would love to be added, armor trims. what i mean by it being able to trim the warden armor. I personally love the trims on all armors and once i just trimmed my whole netherite armor just to lose the trim later, so would greatly appreciate if this feature would be considered, Thank You.
**Additional context**:
Add any other context about the feature here. Any concept art?

**Comment by NewJumper** [comment] 2024-08-12 23:26
duplicate of #193

**Comment by NewJumper** [comment] 2024-08-13 06:30
added in 90f5282cb0e99f05dbaa03a310d2fc6915792a00

**Closed as completed by NewJumper** 2024-08-13 06:30 UTC
Labels: duplicate, feature
