### ISSUE TITLE
Internal server is crashing when entering dimmension

### ISSUE THREAD

**Issue by raftlp** [KyaniteMods/DeeperAndDarker#377] opened 2024-10-07 16:48 UTC
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.2
**Mod Loader**: forge

**Description**:
When i enter the Otheside dimmension the internal server somehow crashes. i can still move freely in the chunks that loaded around the portal but i cant really do anything. Minecraft doesnt crash tho. I also cant exit minecraft in that state. I have to force close.

**To Reproduce**:
1. Go into the dimention
2. See error

**Additional context**:
Im on a custom modpack. I attatched a log. Help would be appreciated
[latest.log](https://github.com/user-attachments/files/17281987/latest.log)

**Comment by raftlp** [comment] 2024-10-09 08:29
I think i found the issue with fix in this post
https://github.com/KyaniteMods/DeeperAndDarker/issues/373
Will see if it works later today

**Comment by NewJumper** [comment] 2024-10-11 04:05
duplicate of #373

**Closed as not planned by NewJumper** 2024-10-11 04:05 UTC
Labels: bug, duplicate
