### ISSUE TITLE
Soul Elytras not working

### ISSUE THREAD

**Issue by BobIsTheGod** [KyaniteMods/DeeperAndDarker#293] opened 2024-03-17 21:46 UTC
[**Minecraft](url) Version**: 1.19.2
**Mod Version**: 1.2.2
**Mod Loader**: forge

**Description**:
The bug does not let me equip my soul elytras

**To Reproduce**:
- Find the new structure
- Get the materials for soul elytra
- Craft it
- Try equipping it
- Doesn't work.
**Screenshots**:
https://github.com/KyaniteMods/DeeperAndDarker/assets/114264061/a34ac89c-4b89-46ec-a108-e8f67bfc333c
**Additional context**:
when i tryed to craft the soul elytra with a normal enchanted elytra, i couldn't equip it...

**Comment by NewJumper** [comment] 2024-03-26 23:59
duplicate of #245

**Closed as not planned by NewJumper** 2024-03-26 23:59 UTC
Labels: bug, duplicate, forge
