### ISSUE TITLE
Soul Elytra Unable to be Equipped

### ISSUE THREAD

**Issue by AleisterShokan** [KyaniteMods/DeeperAndDarker#295] opened 2024-03-24 06:52 UTC
**Minecraft Version**: 1.19.2
**Mod Version**: 1.2.2
**Mod Loader**: forge

**Description**:
Crafted the Soul Elytra but I am unable to equip them in game.

**To Reproduce**:
1. Obtained necessary materials
2. Used enchanted Elytra to craft Soul Elytra
3. Attempted to equip
4. Unable to equip

**Screenshots**:
N/A

**Additional context**:
No other issues so far, was just looking forward to upgraded Elytra, hopefully this gets fixed soon, I saw there was another open ticket from a week ago with the same issue, hopefully the repost helps draw attention.

**Comment by NewJumper** [comment] 2024-03-26 23:59
duplicate of #245 
Please don't repost issues

**Closed as not planned by NewJumper** 2024-03-26 23:59 UTC
Labels: bug
