### ISSUE TITLE
Server crashes when a player joins

### ISSUE THREAD

**Issue by netfix9** [KyaniteMods/DeeperAndDarker#254] opened 2023-12-18 18:45 UTC
**Minecraft Version**: 1.20.2
**Mod Version**: x.x.x
**Mod Loader**: forge/fabric

https://pastebin.com/6SRMt1sM

https://github.com/kyrptonaught/customportalapi/issues/89

https://www.reddit.com/r/admincraft/comments/18l25ih/server_crashes_when_a_player_joins/

**Comment by netfix9** [comment] 2023-12-18 20:22
how do i update the customportalapi version in the mod?

**Comment by Poopooracoocoo** [comment] 2023-12-21 03:34
This can be fixed just by updating https://github.com/KyaniteMods/DeeperAndDarker/blob/9308c1cd46c4c7d2f1d4b38e2b97a22ef3162198/gradle.properties#L18C27-L18C27 to 0.0.1-beta64.5-1.20.2

This is caused by the "Avoid serializing object-based payload into PacketByteBuf on the main thread" changes in Fabric API 0.91.0.

---

You can switch to Fabric API 0.90.7 until Deeper and Darker updates the version of Custom Portal API it uses.

>how do i update the customportalapi version

You can compile it yourself and then add it to your mods folder. Go to the 1.20.2 branch, download as a zip, extract the zip, open the folder in a terminal and run `./gradlew build`. It'll be in the same folder -> build -> libs. Use the non-sources jar. 

(I'm sure there's a way to get it from the maven repo but I don't know how)

**Comment by Pedro270707** [comment] 2024-01-17 23:22
Fixed in 1.2.6

**Closed as completed by Pedro270707** 2024-01-17 23:22 UTC
Labels: bug, compatibility, fabric
