### ISSUE TITLE
Echo boat crashes the game while on fire

### ISSUE THREAD

**Issue by wilsontulus** [KyaniteMods/DeeperAndDarker#147] opened 2023-03-20 03:04 UTC
**Mod Version**: 1.1.6

**Mod Loader**: fabric

**Description**:
Echo boat when on fire crashes the game.

**To Reproduce**:
1. Spawn any Echo boat
2. Set a fire in front of the Echo boat
3. Ride the Echo boat through the fire, also works with lava and lightning
4. Game crash

**Error logs**:
https://pastebin.com/aymfx2jx

**Comment by gamma-02** [comment] 2023-06-04 01:26
this is actually a duplicate of #164, or perhaps that is a duplicate of this. Either way, they are caused by the same thing, a null pointer exception in DDBoat$Type.getItem()

**Comment by NolanHewitt** [comment] 2023-06-04 06:39
I can’t even place an echo boat in the first place.

**Comment by gamma-02** [comment] 2023-06-04 21:45
That doesn't mean the issues are unrelated, and they are both caused by the same thing, your crash report just proves that. 

This is a couple of lines from @wilsontulus's crash report:
`Caused by: java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.item" is null
	at com.kyanite.deeperdarker.registry.entities.custom.DDBoat$Type.getItem(DDBoat.java:113) ~[deeperdarker-fabric-1.1.6-fabric.jar:?]`
and here is the same thing in yours, @NolanHewitt:
`java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.item" is null
	at com.kyanite.deeperdarker.registry.entities.custom.DDBoat$Type.getItem(DDBoat.java:113)`

even if the situation that causes the crash are different, the cause of the crash is the same thing.

**Closed** 2023-06-06 00:05 UTC
Labels: bug
